# Generated by Django 5.1.2 on 2024-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='codigo_professor',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(related_name='turmas', to='app.disciplina'),
        ),
    ]
