# Generated by Django 5.1.2 on 2024-11-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma'),
        ),
    ]
