# Generated by Django 5.1.2 on 2024-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notas_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
