# Generated by Django 5.1.2 on 2024-11-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_notas_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
